include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    # Ignore generated files
    - "**/*.g.dart"
    - "lib/generated/**"
  errors:
    close_sinks: ignore
linter:
  rules:
    unsafe_html: false
